on:
  push:
  pull_request:
  workflow_dispatch:
name: Build Flatpak
jobs:
  flatpak-builder:
    name: "Flatpak Builder"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-6.2
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64, aarch64]
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false
    steps:
    - uses: vicr123/libcontemporary/build-flatpak@actions
      name: "Build Flatpak"
      with:
        arch: ${{ matrix.arch }}
        repo-token: ${{ secrets.REPO_TOKEN }}
        repository: blueprint
        bundle-name: "thefile.flatpak"
        manifest: "dist/com.vicr123.thefile_blueprint.yml"
